version: '3.9'

services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: workatlas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: /start
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

